# Base image
FROM afdaniele/lcm:environment

# set default LCM_VERSION
ENV LCM_VERSION 'master'

# install LCM
RUN \
# pull lcm
    wget https://github.com/lcm-proj/lcm/archive/$LCM_VERSION.zip && \
# open up the source
    unzip $LCM_VERSION.zip && \
# configure, build, install, and configure LCM
    cd lcm-$LCM_VERSION && ./configure && make && make install && ldconfig && \
# delete source code
    rm -rf $LCM_VERSION.zip lcm-$LCM_VERSION
