# Base image
FROM ripl/lcm:latest

# copy, then build examples
COPY assets/examples /root/examples
RUN cd /root/examples/publisher && lcm-gen -p example_t.lcm
RUN cd /root/examples/listener && lcm-gen -p example_t.lcm
