name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load environment variables
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: ./.env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push previous
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ripl/lcm:env.UBUNTU_VERSION_PREVIOUS
          build-args: UBUNTU_VERSION=${{ env.UBUNTU_VERSION_PREVIOUS }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ripl/lcm:latest
          build-args: UBUNTU_VERSION=${{ env.UBUNTU_VERSION_LATEST }}
